""" ArcGIS python toolboxes for ``propagator``.

This contains Classes compatible with ArcGIS python toolbox
infrastructure.

(c) Geosyntec Consultants, 2015.

Released under the BSD 3-clause license (see LICENSE file for more info)

Written by Paul Hobson (phobson@geosyntec.com)

"""


import os
from textwrap import dedent
from collections import OrderedDict

import arcpy
import numpy
try:
    from tqdm import tqdm
except ImportError:
    tqdm = lambda x: x

import propagator
from propagator import utils


class BaseToolbox_Mixin(object):
    canRunInBackground = True

    def isLicensed(self):
        """ PART OF THE ESRI BLACK BOX.

        Esri says:

            Set whether tool is licensed to execute.


        So I just make this always true b/c it's an open source project
        with a BSD license -- (c) Geosyntec Consultants -- so who cares?

        """
        return True

    def updateMessages(self, parameters): # pragma: no cover
        """ PART OF THE ESRI BLACK BOX.

        Esri says:

            Modify the messages created by internal validation for each
            parameter of the tool.  This method is called after internal
            validation.


        But I have no idea when or how internal validation is called so
        that's pretty useless information.

        """
        return

    def updateParameters(self, parameters): # pragma: no cover
        """ PART OF THE ESRI BLACK BOX.

        Automatically called when any parameter is updated in the GUI.

        The general flow is like this:

          1. User interacts with GUI, filling out some input element
          2. ``self.getParameterInfo`` is called
          3. Parameteter are fed to this method as a list

        I used to set the parameter dependecies in here, but that didn't
        work. So now this does nothing and dependecies are set when the
        parameters (as class properties) are created (i.e., called for
        the first time).

        """
        return

    def getParameterInfo(self):
        """ PART OF THE ESRI BLACK BOX

        This *must* return a list of all of the parameter definitions.

        Esri recommends that you create all of the parameters in here,
        and always return that list. I instead chose to create the list
        from the class properties I've defined. Accessing things with
        meaningful names is always better, in my opinion.

        """
        return self._params_as_list()

    def execute(self, parameters, messages): # pragma: no cover
        """ PART OF THE ESRI BLACK BOX

        This method is called when the tool is actually executed. It
        gets passed magics lists of parameters and messages that no one
        can actually see.

        Due to this mysterious nature, I do the following:

        1) turn all of the elements of the list into a dictionary
           so that we can access them in a meaningful way. This
           means, instead of doing something like

        .. code-block:: python

           dem = parameters[0].valueAsText
           zones = parameters[1].valueAsText
           # yada yada
           nth_param = parameters[n].valueAsText

       for EVERY. SINGLE. PARAMETER, we can instead do something like:

        .. code-block:: python

           params = self._get_parameter_values(parameters, multivals=['elevation'])
           dem = params['dem']
           zones = params['zones'].
           # yada

       This is much cleaner, in my opinion, and we don't have to
       magically know where in the list of parameters e.g., the
       DEM is found. Take note, Esri.

        2) generate a list of scenarios usings :meth:`.make_scenarios`.
        3) loop through those scenarios.
        4) call :meth:`.analyze` on each scenario.
        5) call :meth:`.finish_results` on all of the layers
           generated by the loop.

        """

        params = self._get_parameter_values(parameters)
        self.analyze(**params)

        return None

    @staticmethod
    def _set_parameter_dependency(downstream, *upstream):
        """ Set the dependecy of a arcpy.Parameter

        Parameters
        ----------
        downstream : arcpy.Parameter
            The Parameter that is reliant on an upstream parameter.
        upstream : acrpy.Parameters
            An arbitraty number of "upstream" parameters on which the
            "downstream" parameter depends.

        Returns
        -------
        None

        See Also
        --------
        http://goo.gl/HcR6WJ

        """

        downstream.parameterDependencies = [u.name for u in upstream]

    @staticmethod
    def _show_header(title, verbose=True):
        """ Creates and shows a little header from a title.

        Parameters
        ----------
        title : str
            The message to be shown
        verbose : bool, optional (True)
            Whether or not the final message should be printed

        Returns
        -------
        header : str
            The formatted title as a header

        Examples
        --------
        >>> Flooder._show_header('Hello, world', verbose=True)
        'Hello, world'
         --------------

        """
        underline = ''.join(['-'] * len(title))
        header = '\n{}\n{}'.format(title, underline)
        utils._status(header, verbose=verbose, asMessage=True, addTab=False)
        return header

    @staticmethod
    def _add_to_map(layerfile, mxd=None):
        """ Adds a layer or raster to the "CURRENT" map.

        Parameters
        ----------
        layerfile : str
            Path to the layer or raster that will be added
        mxd : str, optional
            Path to an ESRI mapdocument.

        Returns
        -------
        ezmd : EasyMapDoc
            The "easy map document" to which ``layerfile`` was added.

        """
        if mxd is None:
            mxd = 'CURRENT'
        ezmd = utils.EasyMapDoc(mxd)
        if ezmd.mapdoc is not None:
            ezmd.add_layer(layerfile)

        return ezmd

    @staticmethod
    def _get_parameter_values(parameters, multivals=None):
        """ Returns a dictionary of the parameters values as passed in from
        the ESRI black box. Keys are the parameter names, values are the
        actual values (as text) of the parameters.

        Parameters
        ----------
        parameters : list of arcpy.Parameter-type thingies
            The list of whatever-the-hell ESRI passes to the
            :meth:`.execute` method of a toolbox.
        multivals : str or list of str, optional
            Parameter names that can take mulitiple values.

        Returns
        -------
        params : dict
            A python dictionary of parameter values mapped to the
            parameter names.

        """

        if multivals is None:
            multivals = []
        elif numpy.isscalar(multivals):
            multivals = [multivals]

        params = {}
        for p in parameters:
            value = p.valueAsText
            if p.name in multivals:
                value = value.split(';')
            params[p.name] = value

        return params

    @staticmethod
    def _prep_input(**kwargs):
        """ TODO:
        Prepares the basic inputs to the :meth:`.analyze` method.

        Parameters
        ----------
        TODO

        Returns
        -------
        TODO

        """

        return None

    @property
    def workspace(self):
        """ The directory or geodatabase in which the analysis will
        occur.

        """

        if self._workspace is None:
            self._workspace = arcpy.Parameter(
                displayName="Analysis WorkSpace",
                name='workspace',
                datatype="DEWorkspace",
                parameterType="Required",
                direction="Input",
                multiValue=False
            )
        return self._workspace

    @property
    def subcatchments(self):
        """ The subcatchments polygons to be used in the analysis.

        """

        if self._subcatchments is None:
            self._subcatchments = arcpy.Parameter(
                displayName="Subcatchments",
                name="subcatchments",
                datatype="DEFeatureClass",
                parameterType="Required",
                direction="Input",
                multiValue=False
            )
            self._set_parameter_dependency(self._subcatchments, self.workspace)
        return self._subcatchments

    @property
    def ID_column(self):
        """
        Name of the field in the `subcatchments` layer that uniquely
        identifies each subcatchment.

        """

        if self._ID_column is None:
            self._ID_column = arcpy.Parameter(
                displayName="Column with Subcatchment IDs",
                name="ID_column",
                datatype="Field",
                parameterType="Required",
                direction="Input",
                multiValue=False
            )
            self._set_parameter_dependency(self._ID_column, self.subcatchments)
        return self._ID_column

    @property
    def downstream_ID_column(self):
        """
        Name of the field in the `subcatchments` layer that specifies
        the downstream subcatchment.

        """

        if self._ID_column is None:
            self._ID_column = arcpy.Parameter(
                displayName="Column with the Downstream Subcatchment IDs",
                name="downstream_ID_column",
                datatype="Field",
                parameterType="Required",
                direction="Input",
                multiValue=False
            )
            self._set_parameter_dependency(self._downstream_ID_column, self.subcatchments)
        return self._downstream_ID_column

    @property
    def output_layer(self):
        """ Where the propagated/accumulated data will be saved.

        """

        if self._output_layer is None:
            self._output_layer = arcpy.Parameter(
                displayName="Output subcatchments layer/filename",
                name="output_layer",
                datatype="GPString",
                parameterType="Required",
                direction="Input"
            )
        return self._output_layer


class Propagator(BaseToolbox_Mixin):
    """
    ArcGIS Python toolbox to propagate water quality metrics upstream
    through subcatchments in a watershed.

    Parameters
    ----------
    None

    See also
    --------
    Accumulator

    """
    direction = 'upstream'

    def __init__(self):
        """Define the tool (tool name is the name of the class)."""
        # std attributes
        self.label = "1 - Propagate values via subcatchments"
        self.description = dedent("""
        TDB
        """)

        self.multivals = None

        # lazy properties
        self._workspace = None
        self._subcatchments = None
        self._ID_column = None
        self._downstream_ID_column = None
        self._monitoring_locations = None
        self._output_layer = None

    @property
    def monitoring_locations(self):
        """ The monitoring location points whose data will be propagated
        to the subcatchments.

        """

        if self._monitoring_locations is None:
            self._monitoring_locations = arcpy.Parameter(
                displayName="Monitoring Locations",
                name="monitoring_locations",
                datatype="DEFeatureClass",
                parameterType="Required",
                direction="Input",
                multiValue=False
            )
            self._set_parameter_dependency(self._monitoring_locations, self.workspace)
        return self._monitoring_locations

    def _params_as_list(self):
        params = [
            self.workspace,
            self.subcatchments,
            self.ID_column,
            self.downstream_ID_column,
            self.monitoring_locations,
            self.output_layer,
        ]
        return params

    def analyze(self, **params):
        """ Performs the flood-impact analysis on multiple flood
        elevations.

        Parameters
        ----------
        workspace : str
            The folder or geodatabase where the analysis will be
            executed.
        subcatchments, monitoring_locations : str
            Name of the subcatchments and streams layers inside
            ``workspace``.
        output_layer : str
            Name of the new layer inside ``workspace`` where all of the
            results will be save.

        Returns
        -------
        None

        """
        workspace = params.pop('workspace', '.')
        subcatchments = params.pop('subcatchments', None)
        id_col = params.pop('ID_column', None)
        ds_col = params.pop('downstream_ID_column', None)
        monitoring_locations = params.pop('monitoring_locations', None)
        output = params.pop('output_layer', None)
        water_quality_columns = params.pop('water_quality_columns', None)

        with utils.WorkSpace(workspace), utils.OverwriteState(True):
            subcatchment_array = self.prep_water_quality(subcatchments, monitoring_locations)
            for wqcol in water_quality_columns:
                wq = analysis.propagate_scores(subcatchment_array, wqcol)

            analysis.update_water_quality_layer(output_layer, wq)


class Accumulator(BaseToolbox_Mixin):
    """
    ArcGIS Python toolbox to accumulate subcatchments attributes and
    water quality parameters downstream through a stream.

    Parameters
    ----------
    None

    See also
    --------
    Propagator

    """
    direction = 'downstream'

    def __init__(self):
        """Define the tool (tool name is the name of the class)."""
        # std attributes
        self.label = "2 - Accumulate values via subcatchments"
        self.description = dedent("""
        TDB
        """)

        self.multivals = None

        # lazy properties
        self._workspace = None
        self._subcatchments = None
        self._direction = None
        self._streams = None
        self._output_layer = None

    def _params_as_list(self):
        params = [
            self.workspace,
            self.subcatchments,
            self.streams,
            self.output_layer,
        ]
        return params

    @property
    def streams(self):
        """ The streams who will accumulate attributes from
        subcatchments.

        """

        if self._streams is None:
            self._streams = arcpy.Parameter(
                displayName="Streams",
                name="streams",
                datatype="DEFeatureClass",
                parameterType="Required",
                direction="Input",
                multiValue=False
            )
            self._set_parameter_dependency(self._streams, self.workspace)
        return self._streams

    def analyze(self, **params):
        """ Performs the flood-impact analysis on multiple flood
        elevations.

        Parameters
        ----------
        workspace : str
            The folder or geodatabase where the analysis will be
            executed.
        subcatchments, streams : str
            Name of the subcatchments and streams layers inside
            ``workspace``.
        output_layer : str
            Name of the new layer inside ``workspace`` where all of the
            results will be save.

        Returns
        -------
        None

        """

        ws = params.pop('workspace', '.')
        sc = params.pop('subcatchments', None)
        st = params.pop('streams', None)
        lyr = params.pop('output_layer', None)

        utils._status('{}-{}-{}-{}'.format(ws, sc, st, lyr), verbose=True, asMessage=True)
